apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicants-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: applicants-api
  template:
    metadata:
      labels:
        app: applicants-api
    spec:
      containers:
      - name: applicants-api
        image: laeticia640/applicants.api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionString
          value: "Server=mssql-linux;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;"
        - name: HostRabbitmq
          value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: applicants-api
spec:
  selector:
    app: applicants-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
