version: '3'

services:
  user.data:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq

  webmvc:
    image: web:latest
    build:
      context: ./
      dockerfile: Web/Dockerfile
    ports:
    - 8080:80
    container_name: web
    depends_on:
      - applicants.api
      - identity_api
      - jobs_api
    restart: always

  applicants.api:
    image: applicants.api:latest
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;
      - HostRabbitmq=rabbitmq
    build:
      context: ./
      dockerfile: Services/Applicants.Api/Dockerfile
    ports:
    - 8081:80
    container_name: applicants.api
    depends_on:
      - sql.data
      - rabbitmq
    restart: always

  jobs_api:
    image: jobs.api:latest
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
      - HostRabbitmq=rabbitmq
    build:
      context: ./
      dockerfile: Services/Jobs.Api/Dockerfile
    ports:
    - 8083:80
    container_name: jobs_api
    depends_on:
      - sql.data
      - rabbitmq
    restart: always

  identity_api:
    image: identity.api:latest
    environment:
      - RedisHost=user.data:6379
      - HostRabbitmq=rabbitmq
    build:
      context: ./
      dockerfile: Services/Identity.Api/Dockerfile
    ports:
    - 8084:80
    container_name: identity_api
    depends_on:
      - user.data
      - rabbitmq
    restart: on-failure

  sql.data:
    image: mssql-linux:latest
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 1433:1433
    container_name: mssql-linux
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U sa -P "Pass@word" -Q "SELECT 1"
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
