apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-linux
  template:
    metadata:
      labels:
        app: mssql-linux
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: mssql-linux
        image: laeticia640/mssql-linux:latest
        ports:
        - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-linux
spec:
  selector:
    app: mssql-linux
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
